### ISSUE TITLE
Forming a Group

### ISSUE THREAD

**Issue by Paul089** [joachim-gassen/sposm#5]
Hi, 

Is anyone still looking to form a group or still has a spot available in his/hers ? 

Thanks in advance,

Paul

**Comment by piastoczek** [comment]
Hi, I am also still looking to form or join a group.

**Comment by vivienneka** [comment]
Is there a group using Python for the group assignment? I am still looking to join a group.

**Comment by joachim-gassen** [comment]
Seems like we are done forming groups. Great! Closing the issue.
